# PageRank

Albert Tang, Robert Hou, Vedaad Shakib, Franklin Ye

In [1]:
import numpy as np
from Meet import Meet
from create_dictionary import *

# Importing dictionary
data = main()

360


Here is the PageRank algorithm.

There is one modification. P is our transition matrix. Our in class notation had $P_{i, j}$ = edge from $i$ to $j$, with our invariant distribution $\pi$ being $\pi P = \pi$. $\pi$ is a row vector, but numpy handles right eigenvectors, and eigenvectors are column vectors.

Oh no. What do I do???

Fret not. If we take the transpose of both sides, we'll get $P^{T} \pi^{T} = \pi^{T}$, which corresponds to an eigenvalue of 1.

In [13]:
def PageRank(data, weight_dict):
    """ This is our pagerank algorithm.
    
    Inputs:
        data: a dictionary --
                key: name
                value: list of Meet objects
        weight_dict: a dictionary --
                key: competition name
                value: weight of an edge corresponding to that competition
                
    Returns:
        The invariant distribution.
                
    """
    P = np.zeros([len(data), len(data)])
    swimmer_indices = {}
    i = 0
    for key in data:
        if key not in swimmer_indices:
            swimmer_indices[key] = i
            i += 1
        for m in data[key]:
            for swimmer in m.lost_to:
                if swimmer not in swimmer_indices:
                    swimmer_indices[swimmer] = i
                    i += 1
                P[swimmer_indices[swimmer]][swimmer_indices[key]] += weight_dict[m.name]
#                 print('here')
    print(P)
                
    for i in range(len(P)):
        row = P[i]
        total = np.sum(row)
        for j in range(len(row)):
            P[i][j] /= total
    #print(P)

    d = 0.85 #damping
    eps=1.0e-5 #quadratic error
    
    N = P.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    last_v = np.ones((N, 1), dtype=np.float32) * 100
    
    while np.linalg.norm(v - last_v, 2) > eps:
        last_v = v
        v = d * np.matmul(P, v) + (1 - d) / N
    return v

In [10]:
# This is for a default implementation where each edge has a weight of 1
weight_dict = {}
for k in data:
    for m in data[k]:
        if m.name not in weight_dict:
            weight_dict[m.name] = 1

In [11]:
print(data['NAKAMURA, Katsumi'][0].lost_to)
print(data['CAO, Jiwen'][0].lost_to)
print(data['FINA:_World_Cup_No_4_-_2015_Series'][0].lost_to)



['FINA:_World_Cup_No_4_-_2015_Series']
['FINA:_World_Cup_No_4_-_2015_Series', 'NAKAMURA, Katsumi', 'HE, Jianbin']
['NAKAMURA, Katsumi', 'HE, Jianbin', 'CAO, Jiwen', 'SMITH, Daniel', 'XU, Qiheng', 'LIN, Yongqing', 'ZHANG, Qibin', 'SHI, Yang']


In [15]:
rankings = PageRank(data, weight_dict)

[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
final_rankings = list(zip(data.keys(), rankings))

In [28]:
final_rankings = [(i[0], i[1][0]) for i in final_rankings]

In [31]:
min(final_rankings, key=lambda x: x[1])

('DESPLANCHES, Jeremy', 0.00010582932356258123)

In [39]:
max(final_rankings, key=lambda x: x[1])

('BUTT, Suleman', 0.0001094260720790184)